services:
  passkey-demp-app:
    image: "passkey-demo-app:latest"
    container_name: "passkey-demo-app"
    build:
      context: ../../
      dockerfile: etc/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RELYING_PARTY_ID=passkey.andrena.de
      - ACTIVE_PROFILE=prod
      - JAVA_OPTS=-Dcom.sun.security.enableCRLDP=true
